name: hazard_finetune_v100
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake>=3.25
  - ffmpeg
  - pyarrow
  - av
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - pip:
      - -r requirements.v100.txt
